New set of 1-line art
sepandhaghighi/art pull request #131
Opened 2020-07-21 18:53 UTC by sadrasabouri

#### Reference Issues/PRs
#130 
#### What does this implement/fix? Explain your changes.
98 new 1-line art added:
	1. angry birds
  	2. angry face
  	3. angry troll
  	4. at what cost
  	5. barf
  	6. basking in glory
  	7. bear GTFO
	8. bear squiting
	9. boxing
	10. breakdown
	11. careless
	12. chasing
	13. cheers
	14. chicken
	15. confused scratch
	16. crazy
	17. creeper
	18. cry face
	19. cry troll
	20. cute face
	21. dance2
	22. dancing
	23. dear god why
	24. devious smile
	25. disagree
	26. discombobulated
	27. dislike1
	28. dislike2
	29. do you even lift bro?
	30. double flip
	31. dude glasses2
	32. emo dance
	33. excited
	34. exorcism
	35. eye roll
	36. feel perky
	37. fido
	38. fight
	39. fisticuffs
	40. flip friend
	41. fly away
	42. flying
	43. fuck you
	44. happy face
	45. happy hug
	46. hitchhicking
	47. hugger
	48. im a hugger
	49. injured
	50. innocent face
	51. japanese lion face
	52. judgemental
	53. judging
	54. kissing
	55. kitty emote
	56. listening to headphones
	57. looking down
	58. love3
	59. meow
	60. no support
	61. opera
	62. peepers
	63. pointing
	64. pretty eyes
	65. put the table back
	66. resting my eyes
	67. robot3
	68. running
	69. sad and confused
	70. sad and crying
	71. sad face
	72. satisfied
	73. seal
	74. shark face
	75. shy
	76. sleepy
	77. staring
	78. stranger danger
	79. strut
	80. stunna shades
	81. surprised2
	82. taking a dump
	83. tgif
	84. things that can_t be unseen
	85. tidy up
	86. tired
	87. touchy feely
	88. tripping out
	89. trolling
	90. wave dance
	91. whisling
	92. winnie the pooh
	93. winning
	94. wizard2
	95. worried
	96. yun
	97. zombie2
	98. zoned

2020-07-21 22:12 UTC, sepandhaghighi commented
@sadrasabouri Hi
It seems there are some duplicate keys in `art_dic`:
1. suprised2
2. angry face
3. fuck you
Please take a look at codefactor issues ;-)

2020-07-21 22:21 UTC, sepandhaghighi commented
@sadrasabouri Also it seems `point` and `pointing` are duplicated ;-)

2020-07-22 11:38 UTC, sepandhaghighi commented on README.md
> +<a href="https://github.com/sepandhaghighi/art/blob/master/ArtList.ipynb"><img src="https://img.shields.io/badge/Art List-596-orange.svg"></a>
596 or 595 ?

2020-07-22 11:38 UTC, sepandhaghighi commented on README.md
> +		<td align="center">596</td>
596 or 595 ?

2020-07-22 11:40 UTC, sepandhaghighi commented on art/test2.py
> +︻デ┳═ー*----*
please remove this trailing white spaces ;-)

2020-07-23 21:10 UTC, sepandhaghighi commented
@sadrasabouri Hi
I tried to fix all issues related to this PR.
Please take a look at my commits and leave your comments

2020-07-29 11:48 UTC, sepandhaghighi commented
@ssheikholeslami Please review this PR ;-)

**Notice 1** : We have enough time
**Notice 2**: If everything is okay, please merge it after approval

2020-08-12 10:02 UTC, sepandhaghighi commented
@ssheikholeslami 
⏰ Just a friendly reminder 😉

2020-08-19 13:46 UTC, sepandhaghighi commented
@ssheikholeslami
⏰ Just a friendly reminder 😉

2020-08-27 11:37 UTC, sepandhaghighi commented
@ssheikholeslami
⏰ Just another friendly reminder 😉

2020-09-03 17:14 UTC, sepandhaghighi commented
@ssheikholeslami
⏰ Just another friendly reminder 😉

2020-09-10 12:23 UTC, sepandhaghighi commented
@ssheikholeslami
⏰ Just another friendly reminder 😉

2020-09-10 15:22 UTC, ssheikholeslami requested changes

2020-09-10 15:22 UTC, ssheikholeslami commented on otherfile/font_check.py
> +from font_wizard import is_utf8,is_ascii
should be `from font_wizard import is_utf8, is_ascii`

2020-09-11 11:55 UTC, ssheikholeslami approved these changes

2020-09-11 12:05 UTC, merged