Modernize code
sepandhaghighi/art pull request #251
Opened 2023-07-20 20:04 UTC by eumiro

1. Remove useless default encoding for source files (UTF-8 is the default)
2. Simplify loops and conditions

2023-07-20 20:48 UTC, sepandhaghighi requested changes
@eumiro Well done 💯 

Please take a look at my comment about **default encoding** and also:

1. Update `CHANGELOG.md`
2. Update `AUTHORS.md`

2023-07-20 20:48 UTC, sepandhaghighi commented on art/__init__.py
> -# -*- coding: utf-8 -*-
Would you please revert this default encoding?
We need this one for some special cases.

2023-07-21 14:26 UTC, eumiro commented
Thank you for the feedback, @sepandhaghighi. Dropped the commit with the `coding` removal and updated `AUTHORS.md`. The other commit is a pure refactoring, so it does not really make sense to add it to `CHANGELOG.md`. It does not change any functionality of the code.

2023-07-21 20:43 UTC, sadrasabouri approved these changes
LGTM

2023-07-24 15:56 UTC, sepandhaghighi approved these changes
🚀

2023-07-24 15:56 UTC, merged