Add/line function
sepandhaghighi/art pull request #283
Opened 2024-10-18 23:09 UTC by AHReccese

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-10-19 09:44 UTC, sepandhaghighi requested changes
Thanks for your efforts 💯 
1. Here(https://github.com/sepandhaghighi/art/pull/283/commits/90679af1a5f1187035878d56978c372c2b783759), I made some changes to fix tests, so please update your local branch

2. Take a look at my comments

3. Add `lprint` and `line` functions to `__init__.py`

4. Add some tests for `lprint` and `line` at the top of `tests/test.py`

⚠️ We will update `README.md` in another pull request.

2024-10-19 09:44 UTC, sepandhaghighi commented on art/functions.py
> +    :param char: target character to print a grid of
target character<s> to print a grid of</s>

2024-10-19 09:44 UTC, sepandhaghighi commented on art/functions.py
> +    :param char: target character to generate a grid of
target character<s> to generate a grid of</s>

2024-10-19 09:44 UTC, sepandhaghighi commented on art/functions.py
> +    if not isinstance(char, str) or len(char) != 1:
Remove `len(char) != 1` (to support non-ascii characters)

2024-10-19 09:44 UTC, sepandhaghighi commented on art/params.py
> +CHAR_TYPE_ERROR = "The 'char' type must be str and has length of 1."
"The 'char' type must be str<s> and has length of 1</s>."

2024-10-19 09:44 UTC, sepandhaghighi commented on art/params.py
> +HEIGHT_RANGE_ERROR = "The `height` parameter should be >= 1."
`height` --> 'height'

2024-10-19 09:44 UTC, sepandhaghighi commented on art/params.py
> +LENGTH_RANGE_ERROR = "The `length` parameter should be >= 1."
`length` --> 'length'

2024-10-19 09:44 UTC, sepandhaghighi commented on art/functions.py
> +    return "\n".join([line_str for _ in range(height)])
```python
"\n".join([line_str] * height)
```

2024-10-22 12:11 UTC, sepandhaghighi approved these changes
LGTM 🔥

2024-10-22 19:03 UTC, sadrasabouri approved these changes
LGTM :rocket:

2024-10-22 19:04 UTC, merged