Minor edits on line functionality
sepandhaghighi/art pull request #285
Opened 2024-10-26 23:30 UTC by sadrasabouri

#### Reference Issues/PRs
#272 
#### What does this implement/fix? Explain your changes.
Minor edits in test systems, error messages, and readme.

Note: readme was already updated so this PR won't update that file.

2024-10-28 06:03 UTC, sepandhaghighi requested changes
@sadrasabouri 
Thanks for your effort 💯 
Please take a look at my comments

2024-10-28 06:03 UTC, sepandhaghighi commented on README.md
> +### 4. lprint
I believe that the `lprint` and `line` functions are not part of the `## ASCII text` section. We need to create a new section named `Line` to include both of these functions.

2024-10-28 06:03 UTC, sepandhaghighi commented on art/params.py
> +LENGTH_ERROR = "The 'length' must be an int higher than 0."
`LENGTH_ERROR` --> `LINE_LENGTH_ERROR`

2024-10-28 06:03 UTC, sepandhaghighi commented on art/params.py
> +HEIGHT_ERROR = "The 'height' must be an int higher than 0."
`HEIGHT_ERROR` --> `LINE_HEIGHT_ERROR`

2024-10-28 20:45 UTC, sadrasabouri commented
All fixed, please re-review it @sepandhaghighi

2024-11-02 22:33 UTC, sepandhaghighi requested changes

2024-11-02 22:33 UTC, sepandhaghighi commented on README.md
> +## Line
`### Line`

2024-11-02 22:33 UTC, sepandhaghighi commented on README.md
> +### 1. lprint
`####`

2024-11-02 22:33 UTC, sepandhaghighi commented on README.md
> +### 2. line
`####`

2024-11-02 22:33 UTC, sepandhaghighi commented on README.md
> +* Note1: This feature has been added since `Version 6.4`.
Remove `.`

2024-11-02 22:33 UTC, sepandhaghighi commented on README.md
> +* Note2: The default values are `length=15`, `height=1`, `char='#'`.
Remove `.`

2024-11-02 22:33 UTC, sepandhaghighi commented on README.md
> +* Note1: This feature has been added since `Version 6.4`.
Remove `.`

2024-11-02 22:33 UTC, sepandhaghighi commented on README.md
> +* Note2: The default values are `length=15`, `height=1`, `char='#'`.
Remove `.`

2024-11-14 09:16 UTC, sepandhaghighi approved these changes
🔥

2024-11-14 09:17 UTC, merged